### PR TITLE
feat(#43) [TECH] - Session Layer get random question

### PR DESCRIPTION
**Pull request by MelnychenkoIvan**
## PR Checklist

PR meets the following requirements:

- [ ] Changes follow our [guidelines](https://github.com/extreme-startup/questionator/wiki/Contributing)
- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

## PR Type

PR introduces the following changes:

```
[ ] Bugfix
[ x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## Actual/New behavior
Add `getRandom` method to the question service

Issue Number: #43

### CODE REVIEW

**Comment by mrproper1337** [comment]
I which way is it related to #43? I think If you need anything from question service you'd better mock it, as question creation behavior will be implemented as part of #24/#23

**Comment by MelnychenkoIvan** [comment]
@mrproper1337 thank you for the comment I will discus it with our team

**Comment by MelnychenkoIvan** [comment]
> I think If you need anything from question service you'd better mock it, as question creation behavior will be implemented as part of #24/#23

**Comment by MelnychenkoIvan** [comment]
@mrproper1337 thank you for the comment I will discus it with our team

**Comment by MelnychenkoIvan** [comment]
Regarding to the discussion in the slack channel we decided to proceed with this PR.

**Pull request merged**
